<?php


namespace app\components;


use app\models\Category;
use yii\base\Widget;

class MenuWidget extends Widget
{
    public $tpl;
    public $div_class;
    public $data;
    public $tree;
    public $menuHtml;

        public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if ($this->div_class === null) {
            $this->div_class = 'menu';
        }

        if ($this->tpl === null) {
            $this->tpl = 'menu';
        }
        $this->tpl .= '.php';
    }

    public function run()
    {
        $this->data = Category::find()->all();
        debug($this->data);
        return $this->tpl;
    }
}