<?php
/**
 * Created by PhpStorm.
 * File: AppController.php
 * Date: 16/07/2020
 * Time: 23:31
 */

namespace app\controllers;


use yii\web\Controller;

class AppController extends Controller
{
    public function beforeAction($action)
    {
        $this->view->title = \Yii::$app->name;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}